name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install sudo package
      run:  sudo apt update && sudo apt install sudo
    - name: build_all
      run: ./picsimlab_build_all_and_install.sh
