name: C/C++ CI

on:
  workflow_run:
    workflows: ["Release setup"]
    types: [completed]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '!minor')"
    runs-on: ubuntu-18.04

    steps:
    
    - name: Job info
      run: |
        echo "GitHub Ref: ${{ github.ref }}"
        echo "Event: ${{ github.event }}"
    
    - name: checkout sources
      uses: actions/checkout@v2

        #- name: Install sudo package
        #run:  apt update && apt install sudo
    
    - name: build_all_static
      run: ./picsimlab_build_all_static.sh exp

    - name: package artifacts
      run: |
        ./picsimlab_build_package.sh
        ./picsimlab_build_package.sh exp
        ./picsimlab_build_appimage.sh
        ./picsimlab_build_appimage.sh exp
        source .github/workflows/scripts/set_version.sh
        #export VERSION_="${VERSION}_${DATE}"
        #echo "Version is: ${VERSION_}"

    - uses: actions/upload-artifact@v2
      with:
        name: picsimlab_pkg
        path: release*/*

    - name: continuous release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/master' 
      with:
        prerelease: true
        files: release_*/*
        tag_name: continuous
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - if: (startsWith(github.ref, 'refs/tags/')) 
      name: tagged release
      uses: softprops/action-gh-release@v1
      with:
        files: release_*/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

